#!/bin/bash

DIR="$HOME/.ssh"

echo "Enumerating lastpass managed SSH entries..."
for i in `lpass ls "Secure Notes\SSH\managed" | grep "id:" | awk -F ":" '{ print $2 }'| rev | cut -c 2- | rev`
do
    NAME=`lpass show -j $i | jq -r '.[0].name'`
    # perform sanity check - does such a managed ssh key already exist?
    if [ -f "${DIR}/${NAME}_rsa" ]; then
        echo "${DIR}/${NAME}_rsa already exists, skipping..."
    else
      echo "Installing ${NAME}_rsa ..."
      lpass show --field="Private Key" $i > ${DIR}/${NAME}_rsa
      lpass show --field="Public Key" $i > ${DIR}/${NAME}_rsa.pub
      chmod 600 ${DIR}/*
    fi
done
